### PR TITLE
Feature: Support for deps.edn-only projects

### LINKED ISSUE #75: CLI and tools.deps support
Lots of projects now use [tools.deps with the Clojure CLI.](https://clojure.org/guides/deps_and_cli)

Personally, I haven't used leiningen in over a year and avoid uberjar whereever I can (and I very well can with tools.deps!)

If a project has a `deps.edn` it can be run directly (no uberjars needed):
`clj -m my-project.main`

This is a much simpler, lightweight and flexible approach. It would be awesome if heroku supported it, especially given that it looks like the Clojure CLI is already installed by this buildpack.

### PR DESCRIPTION
**Pull request by cap10morgan**
Closes #75

This detects when projects only have a `deps.edn` file and uses the Clojure CLI tools to build and run the app instead of lein. I have tested it with one of my deps.edn apps and it is working there.

### CODE REVIEW

**Comment by cap10morgan** [comment]
Should I point the tests at this fork for now? They pass when I do that locally.

**Comment by cap10morgan** [comment]
@heroku/languages any chance this can get reviewed if I rebase on main?

**Comment by Malax** [comment]
Hey @cap10morgan! Sorry for the long delay on this, my apologies! This is a IMO great addition to the buildpack, thanks for working on this!

I won't have time to review this immediately, but I should have some time next week. Feel free to ping me directly in the future so we can get this over the finish line! :)

**Comment by cap10morgan** [comment]
@Malax Ready for review whenever you get a moment (and thanks again!)

**Comment by Malax** [comment]
@cap10morgan I've just pulled your branch into this repo so that CI can run (we disable CI for external PR's to avoid leaking credentials). As you can see, it went through without a hitch. I'll continue with a code review as the next step! :)

**Comment by cap10morgan** [comment]
@Malax any updates on this? Let me know if there is anything else I can do to move this forward on my end. Thanks!

**Review by edmorley — COMMENTED** [review]
(I'm about to enable review reminder for team-alias reviews, so I'm switching any reviews that need language-owner review to the owner directly, to prevent reminders the rest of the team can't action)

**Comment by skydread1** [comment]
Hi, any updates on this?
I will really like to see this feature available as we use deps.edn only as well.

**Comment by versality** [comment]
+1
We're also building a deps.edn only project and considering to use Heroku. Would be great to have it merged.

**Comment by cap10morgan** [comment]
I no longer use Heroku and wouldn't even be willing to resolve the conflicts in here at this point. I recommend seeking out hosting platforms that give a shit instead.

**Pull request closed without merging**
