### PR TITLE
Export RING_ENV by default to production

### PR DESCRIPTION
**Pull request by wjlroe**
This pull request adds a default environment variable RING_ENV (an analogue to Node's NODE_ENV, Rack's RACK_ENV etc.).

### CODE REVIEW

**Comment by jkutner** [comment]
LGTM. Thanks.

**Comment by wjlroe** [comment]
The Travis build was failing and after much experimentation I have narrowed it down to the difference between:

`SHUNIT_HOME=/tmp/shunit2-2.1.6 /tmp/testrunner/bin/run -c .` <- this fails (fast)

and:

`SHUNIT_HOME=/tmp/shunit2-2.1.6 /tmp/testrunner/bin/run .` <- this works (but takes ages on my VM)

Something to do with the curl caching was causing it to quit and I don't know what that was.

**Comment by wjlroe** [comment]
Oh I see that's the change made on master :smiley_cat:

**Comment by jkutner** [comment]
Yea, sorry about that. It has to do with an update to the [jvm-common](https://github.com/heroku/heroku-buildpack-jvm-common) buildpack, which is used by this buildpack. I added a head request to check if a file exists, and it seems to not play well with testrunner caching.

really sorry about the trouble you probably went through investigating this :(

**Pull request merged**
