### PR TITLE
Added background ssh agent for cli tools requiring private repos

### PR DESCRIPTION
**Pull request by AlexAti**

### CODE REVIEW

**Comment by jkutner** [comment]
I'm hesitant to accept this, because it could have unforeseen impacts on apps that aren't using ssh-agent. The ssh-agent is really meant for a human using a terminal (so they don't have to keep entering their password over and over again). I feel like jsch should really be able to take a key as input, rather than depending on a running service.

Can we explore that idea before I consider accepting this?

**Comment by AlexAti** [comment]
Looking into clojure's docs for this at https://github.com/clojure/tools.gitlibs#ssh-authentication-for-private-repositories, they explicitly state that they expect ssh-agent... and looking into jsch documentation and [usage examples](https://github.com/ymnk/jsch-agent-proxy/blob/master/examples/src/main/java/com/jcraft/jsch/agentproxy/examples/UsingSSHAgent.java), there doesn't seem a way to provide the key.

**Comment by AlexAti** [comment]
I've been looking more into this. Just adding an empty ssh-agent isn't going to cut it, and clojure expects the agent to already have the keys - there doesn't seem to be a way to configure it directly.

So either the clojure buildpack manages directly the reception of ENV variables to receive keys (which is a little bit overkill as private repos through deps are not (yet?) a standard use case of a clojure app), or we rely on a previous buildpack to manage the set up of ssh keys. The problem is that heroku doesn't have an official one, and the ones found in the buildpack registry don't seem to work with the standard clojure buildpack for some reason.

Either way, this pull request doesn't make sense.

@jkutner any ideas on how to move forward? Thanks a lot for the support!

**Comment by jkutner** [comment]
@AlexAti it sounds like a special gitlab-ssh buildpack might do the trick. It could set up ssh in `bin/compile` like:

```
mkdir -p $HOME/.ssh
echo "GITLAB_PRIVATE_KEY" > $HOME/.ssh/id_rsa
echo "GITLAB_PUBLIC_KEY" > $HOME/.ssh/id_rsa.pub
echo "GITLAB_AUTH_KEYS" > $HOME/.ssh/authorized_keys
cat << EOF > $HOME/.ssh/sshd_config
HostKey $HOME/.ssh/id_rsa
AuthorizedKeysFile $HOME/.ssh/authorized_keys
UsePrivilegeSeparation no
EOF
```

Then start `ssh-agent` like in this buildpack. I'm not sure if the ssh-agent process will carry over (or just die) when the next buildpack runs. If it does, I'd be willing to put some kind of hook in this buildpack that can "detect" that the ssh-agent should be started (like it sees the `.ssh` dir or whatever).

**Comment by AlexAti** [comment]
That's basically what I am doing as prelude to the clojure buildpack, to have ssh-agent launched; I think it is more flexible to keep ssh-agent management out of the clojure buildpack. I forked an existing buildpack from the buildpack registry, though, and I'm trying to fix/enhance it.

It eluded me for a while but now I finally found the issue. When ssh-agent is launched in a prior buildpack, it returns information as environment variables, that can be used to connect to it. And between buildpacks, even if the ssh-agent keeps running, the environment variables are lost - so clojure doesn't find the running ssh-agent.

I'm now (https://github.com/AlexAti/custom-ssh-key-buildpack/commit/828ad28854e330ea40f5591cabc002ecb2316564) writing that information on the $build_dir/export script, but when execution reaches the clojure buildpack, export is not being executed. @jkutner, is this evaluation something that should be done inside the clojure buildpack (it isn't, currently), or something done in the heroku infrastructure before calling each buildpack?

**Comment by jkutner** [comment]
The Heroku platform is responsible for sourcing the `export` script from previous buildpacks. But I think you are writing the `export` file to the wrong location. It should be in the `buildpack_dir`, and not the `$BUILD_DIR`:
https://devcenter.heroku.com/articles/buildpack-api#composing-multiple-buildpacks

I think you'll want something like this:

```bash
BP_DIR=$(cd "$(dirname "${0:-}")"; cd ..; pwd)

echo "#!/usr/bin/env bash" >> $BP_DIR/export
```

**Comment by AlexAti** [comment]
Brilliant! Thanks a lot!

**Pull request closed without merging**
